name: Deploy report to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment from

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Report
        run: |
          mkdir -p output
          cp source/report.html output/${{github.run_id}}.html

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          name: ai-eval-report
          path: output/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ai-eval-report
    
      - name: Writing Markdown
        run: |
          echo '### AI Evaluation Report Output' >> $GITHUB_STEP_SUMMARY          
          echo '${{ steps.deployment.outputs.page_url }}/${{github.run_id}}.html' >> $GITHUB_STEP_SUMMARY          