name: Deploy report to GitHub Pages

on:
  push:
    branches:
      - main # or the branch you want to trigger the deployment from

env:
  PAGES_SITE_URL: "https://peterwald.github.io/ghp/"

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        run: |
          HAS_RUN_ID=$(curl -s -o /dev/null -w "%{http_code}" $PAGES_SITE_URL/last_run_id.txt)
          if [ $HAS_RUN_ID -ne 200 ]; then
            echo "No previous run ID found."
          else
            LAST_RUN_ID=$(curl -s $PAGES_SITE_URL/last_run_id.txt)
            echo "Last run ID: $LAST_RUN_ID"
            echo "LAST_RUN_ID=$LAST_RUN_ID" >> $GITHUB_ENV
          fi

      - name: Download previous reports
        uses: actions/download-artifact@v4
        if: ${{ env.LAST_RUN_ID != '' }}
        with:
          name: ai-eval-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ env.LAST_RUN_ID }}
          path: prior-reports/

      - name: Restore Old Reports
        if: ${{ env.LAST_RUN_ID != '' }}
        run: |
          mkdir -p output/
          tar xvf prior-reports/artifact.tar -C output/
          ls -laR output

      - name: Build Report
        run: |
          mkdir -p output/
          cp source/report.html output/${{github.run_id}}.html
          ls -laR output

      - name: Save last run ID
        run: |
          echo "${{github.run_id}}" > output/last_run_id.txt

      - name: Upload all output files as pages artifact
        id: output-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: ai-eval-report
          path: output/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ai-eval-report
    
      - name: Writing Markdown
        run: |
          echo '### AI Evaluation Report Output' >> $GITHUB_STEP_SUMMARY          
          echo '${{ steps.deployment.outputs.page_url }}${{github.run_id}}.html' >> $GITHUB_STEP_SUMMARY          